insert into PEOPLE(PERSON_ID, PERSON_NAME, PERSON_AGE) values(10, 'Proba Peter', 20);
insert into PEOPLE(PERSON_ID, PERSON_NAME, PERSON_AGE) values(20, 'Har Monika', 25);

insert into FOOD_DIARY(food_Id, FOOD_NAME, GRAMS, CALORIES_PER_GRAM, EAT_TIME, PERSON_ID) values(100, 'Keksz', 100, 5, 24523412, 10);
insert into FOOD_DIARY(food_Id, FOOD_NAME, GRAMS, CALORIES_PER_GRAM, EAT_TIME, PERSON_ID) values(200, 'Muzli', 80, 15, 24633416, 20);